server:
  port: 8081

spring:
  application:
    name: price-aggregator
  main:
    allow-bean-definition-overriding: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    async:
      request-timeout: -1

# Swagger/OpenAPI (должен быть на корневом уровне, НЕ внутри spring!)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: ru.retail.service.controller
  show-actuator: false

apify:
  enabled: false
  api:
    token: apify_api_yUzydG8Qrpt5gkdTGO6WdHLVRtDR5a4j9qoD
    base-url: https://api.apify.com
  actor:
    drom-scraper-id: Lz2PWiyvRnFjoINKV

drom:
  headless: false  # false для отладки, true для продакшена
  proxy:
    url: http://sUxCAy:aTYcmATpajez@mproxy.site:16532

twocaptcha:
  enabled: true   # true для автоматического решения капчи
  api-key: 682948916e47240f5ce9a73ec7c1f4a4 # Ключ с 2captcha.com

gemini:
  api:
    key: sk-7ug6l6ES8RO6Ws10VL6vbA
    base-url: https://open.blackroute.space/v1/chat/completions
  vision:
    model: gemini-3.5-flash

deepseek:
  api:
    token: sk-v0VUKD3dAXgYlikrioAGwQ
    base-url: https://open.blackroute.space/v1/chat/completions
  text:
    model: deepseek-chat

#    sk-70c0e9c831ec41568ade1fa9124aeeb8

feign:
  client:
    config:
      apify-actor-client:
        connectTimeout: 30000
        readTimeout: 300000
        loggerLevel: FULL
      apify-dataset-client:
        connectTimeout: 10000
        readTimeout: 60000
        loggerLevel: FULL

logging:
  level:
    ru.retail.service.client: DEBUG
    feign: DEBUG
    ru.retail.service.service.AIPriceAdvisor: DEBUG
    ru.retail.service.controller: DEBUG